apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
build:
  googleCloudBuild:
    projectId: ticketing-dev-278807    
  artifacts:
    - image: us.gcr.io/ticketing-dev-278807/auth
      context: auth
      docker: 
        dockerfile: DOckerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: . 